declare var com, android, java: any;

export const AudioManager = android.media.AudioManager ;
export const AudioAttributes = android.media.AudioAttributes;
export const AudioFocusRequest = android.media.AudioFocusRequest;
export const LocalParticipant = com.twilio.video.LocalParticipant;
export const RoomState = com.twilio.video.RoomState;
export const Video = com.twilio.video.Video;
export const VideoRenderer = com.twilio.video.VideoRenderer;
export const TwilioException = com.twilio.video.TwilioException;
export const AudioTrack = com.twilio.video.AudioTrack;
export const CameraCapturer = com.twilio.video.CameraCapturer;
export const CameraCapturerCameraSource = com.twilio.video.CameraCapturer.CameraSource;
export const ConnectOptions = com.twilio.video.ConnectOptions;
export const LocalAudioTrack = com.twilio.video.LocalAudioTrack;
export const LocalVideoTrack = com.twilio.video.LocalVideoTrack;
export const VideoCapturer = com.twilio.video.VideoCapturer;
export const RemoteParticipant = com.twilio.video.RemoteParticipant;
export const Room = com.twilio.video.Room;
export const VideoTrack = com.twilio.video.VideoTrack;
export const AudioCodec = com.twilio.video.AudioCodec;